# Generated by Django 2.2.13 on 2020-06-12 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_songsdetail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SongsDetails',
        ),
    ]
