# Generated by Django 2.2.13 on 2020-06-12 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SongsDetails',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=1000)),
                ('artist', models.CharField(max_length=1000)),
                ('top_genre', models.CharField(max_length=1000)),
                ('year', models.IntegerField()),
                ('bpm', models.IntegerField()),
                ('nrgy', models.IntegerField()),
                ('dnce', models.IntegerField()),
                ('dB', models.IntegerField()),
                ('live', models.IntegerField()),
                ('val', models.IntegerField()),
                ('dur', models.IntegerField()),
                ('acous', models.IntegerField()),
                ('spch', models.IntegerField()),
                ('pop', models.IntegerField()),
            ],
        ),
    ]
