# Generated by Django 2.2.13 on 2020-06-16 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_newsongdetails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewSongDetails',
        ),
    ]
