# Generated by Django 2.2.13 on 2020-06-16 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_newsongdetails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewSongDetails',
        ),
    ]
