# Generated by Django 2.2.13 on 2020-06-16 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_delete_newsongdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewSongDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SongID', models.CharField(max_length=1000)),
                ('Performer', models.CharField(max_length=1000)),
                ('Song', models.CharField(max_length=1000)),
                ('spotify_genre', models.CharField(max_length=1000)),
                ('spotify_track_album', models.CharField(max_length=1000)),
                ('spotify_track_explicit', models.DecimalField(decimal_places=4, max_digits=5)),
                ('spotify_track_duration_ms', models.DecimalField(decimal_places=4, max_digits=5)),
                ('spotify_track_popularity', models.DecimalField(decimal_places=4, max_digits=5)),
                ('danceability', models.DecimalField(decimal_places=4, max_digits=5)),
                ('energy', models.DecimalField(decimal_places=4, max_digits=5)),
                ('key', models.DecimalField(decimal_places=4, max_digits=5)),
                ('loudness', models.DecimalField(decimal_places=4, max_digits=5)),
                ('mode', models.DecimalField(decimal_places=4, max_digits=5)),
                ('speechiness', models.DecimalField(decimal_places=4, max_digits=5)),
                ('acousticness', models.DecimalField(decimal_places=4, max_digits=5)),
                ('liveness', models.DecimalField(decimal_places=4, max_digits=5)),
                ('valence', models.DecimalField(decimal_places=4, max_digits=5)),
                ('tempo', models.DecimalField(decimal_places=4, max_digits=5)),
                ('time_signature', models.DecimalField(decimal_places=4, max_digits=5)),
                ('WeekID', models.CharField(max_length=1000)),
            ],
        ),
    ]
