# Generated by Django 2.2.13 on 2020-06-16 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_newersongsdetails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewSongDetails',
        ),
        migrations.DeleteModel(
            name='SongsDetail',
        ),
    ]
