# Generated by Django 2.2.13 on 2020-06-16 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_newsongdetails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewSongDetails',
        ),
    ]
